<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/03/30 12:19:25

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=ilyathica',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
